version: '3.1'

services:
  db:
    image: "postgres:latest"
    restart: "no" 
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
